// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocalNetDevice.proto

package com.nesp.sdk.kotlin.localnet.device.protocol;

public interface LocalNetDeviceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * device identifier.
   * </pre>
   *
   * <code>optional string did = 1;</code>
   * @return Whether the did field is set.
   */
  boolean hasDid();
  /**
   * <pre>
   * device identifier.
   * </pre>
   *
   * <code>optional string did = 1;</code>
   * @return The did.
   */
  java.lang.String getDid();
  /**
   * <pre>
   * device identifier.
   * </pre>
   *
   * <code>optional string did = 1;</code>
   * @return The bytes for did.
   */
  com.google.protobuf.ByteString
      getDidBytes();

  /**
   * <pre>
   * user id, empty if user is not login.
   * </pre>
   *
   * <code>optional string uid = 2;</code>
   * @return Whether the uid field is set.
   */
  boolean hasUid();
  /**
   * <pre>
   * user id, empty if user is not login.
   * </pre>
   *
   * <code>optional string uid = 2;</code>
   * @return The uid.
   */
  java.lang.String getUid();
  /**
   * <pre>
   * user id, empty if user is not login.
   * </pre>
   *
   * <code>optional string uid = 2;</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <pre>
   * device ip address.
   * </pre>
   *
   * <code>optional string ip = 3;</code>
   * @return Whether the ip field is set.
   */
  boolean hasIp();
  /**
   * <pre>
   * device ip address.
   * </pre>
   *
   * <code>optional string ip = 3;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <pre>
   * device ip address.
   * </pre>
   *
   * <code>optional string ip = 3;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   * port for udp
   * </pre>
   *
   * <code>optional int32 udp_port = 4;</code>
   * @return Whether the udpPort field is set.
   */
  boolean hasUdpPort();
  /**
   * <pre>
   * port for udp
   * </pre>
   *
   * <code>optional int32 udp_port = 4;</code>
   * @return The udpPort.
   */
  int getUdpPort();

  /**
   * <pre>
   * flag for addition information
   * </pre>
   *
   * <code>optional int32 flag = 5;</code>
   * @return Whether the flag field is set.
   */
  boolean hasFlag();
  /**
   * <pre>
   * flag for addition information
   * </pre>
   *
   * <code>optional int32 flag = 5;</code>
   * @return The flag.
   */
  int getFlag();

  /**
   * <pre>
   * device linked count, -1 is not enabled.
   * </pre>
   *
   * <code>optional int32 linked_count = 6;</code>
   * @return Whether the linkedCount field is set.
   */
  boolean hasLinkedCount();
  /**
   * <pre>
   * device linked count, -1 is not enabled.
   * </pre>
   *
   * <code>optional int32 linked_count = 6;</code>
   * @return The linkedCount.
   */
  int getLinkedCount();

  /**
   * <pre>
   * device name.
   * </pre>
   *
   * <code>optional string name = 7;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   * device name.
   * </pre>
   *
   * <code>optional string name = 7;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * device name.
   * </pre>
   *
   * <code>optional string name = 7;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * device model.
   * </pre>
   *
   * <code>optional string model = 8;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <pre>
   * device model.
   * </pre>
   *
   * <code>optional string model = 8;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <pre>
   * device model.
   * </pre>
   *
   * <code>optional string model = 8;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <pre>
   * device machine brand
   * </pre>
   *
   * <code>optional string brand = 9;</code>
   * @return Whether the brand field is set.
   */
  boolean hasBrand();
  /**
   * <pre>
   * device machine brand
   * </pre>
   *
   * <code>optional string brand = 9;</code>
   * @return The brand.
   */
  java.lang.String getBrand();
  /**
   * <pre>
   * device machine brand
   * </pre>
   *
   * <code>optional string brand = 9;</code>
   * @return The bytes for brand.
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <pre>
   * device board
   * </pre>
   *
   * <code>optional string board = 10;</code>
   * @return Whether the board field is set.
   */
  boolean hasBoard();
  /**
   * <pre>
   * device board
   * </pre>
   *
   * <code>optional string board = 10;</code>
   * @return The board.
   */
  java.lang.String getBoard();
  /**
   * <pre>
   * device board
   * </pre>
   *
   * <code>optional string board = 10;</code>
   * @return The bytes for board.
   */
  com.google.protobuf.ByteString
      getBoardBytes();

  /**
   * <pre>
   *0: UnKnown 1: Android 2: IOS 3: Linux 4: Windows 5: MacOS 6: HarmonyOS 7: Fuchsia
   * </pre>
   *
   * <code>optional .com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice.SystemType system_type = 11;</code>
   * @return Whether the systemType field is set.
   */
  boolean hasSystemType();
  /**
   * <pre>
   *0: UnKnown 1: Android 2: IOS 3: Linux 4: Windows 5: MacOS 6: HarmonyOS 7: Fuchsia
   * </pre>
   *
   * <code>optional .com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice.SystemType system_type = 11;</code>
   * @return The enum numeric value on the wire for systemType.
   */
  int getSystemTypeValue();
  /**
   * <pre>
   *0: UnKnown 1: Android 2: IOS 3: Linux 4: Windows 5: MacOS 6: HarmonyOS 7: Fuchsia
   * </pre>
   *
   * <code>optional .com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice.SystemType system_type = 11;</code>
   * @return The systemType.
   */
  com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice.SystemType getSystemType();

  /**
   * <pre>
   * system name.
   * </pre>
   *
   * <code>optional string system_name = 12;</code>
   * @return Whether the systemName field is set.
   */
  boolean hasSystemName();
  /**
   * <pre>
   * system name.
   * </pre>
   *
   * <code>optional string system_name = 12;</code>
   * @return The systemName.
   */
  java.lang.String getSystemName();
  /**
   * <pre>
   * system name.
   * </pre>
   *
   * <code>optional string system_name = 12;</code>
   * @return The bytes for systemName.
   */
  com.google.protobuf.ByteString
      getSystemNameBytes();

  /**
   * <pre>
   * system version code
   * </pre>
   *
   * <code>optional int32 system_version_code = 13;</code>
   * @return Whether the systemVersionCode field is set.
   */
  boolean hasSystemVersionCode();
  /**
   * <pre>
   * system version code
   * </pre>
   *
   * <code>optional int32 system_version_code = 13;</code>
   * @return The systemVersionCode.
   */
  int getSystemVersionCode();

  /**
   * <pre>
   * system version name
   * </pre>
   *
   * <code>optional string system_version_name = 14;</code>
   * @return Whether the systemVersionName field is set.
   */
  boolean hasSystemVersionName();
  /**
   * <pre>
   * system version name
   * </pre>
   *
   * <code>optional string system_version_name = 14;</code>
   * @return The systemVersionName.
   */
  java.lang.String getSystemVersionName();
  /**
   * <pre>
   * system version name
   * </pre>
   *
   * <code>optional string system_version_name = 14;</code>
   * @return The bytes for systemVersionName.
   */
  com.google.protobuf.ByteString
      getSystemVersionNameBytes();

  /**
   * <pre>
   * system arch
   * </pre>
   *
   * <code>optional string system_arch = 15;</code>
   * @return Whether the systemArch field is set.
   */
  boolean hasSystemArch();
  /**
   * <pre>
   * system arch
   * </pre>
   *
   * <code>optional string system_arch = 15;</code>
   * @return The systemArch.
   */
  java.lang.String getSystemArch();
  /**
   * <pre>
   * system arch
   * </pre>
   *
   * <code>optional string system_arch = 15;</code>
   * @return The bytes for systemArch.
   */
  com.google.protobuf.ByteString
      getSystemArchBytes();

  /**
   * <pre>
   * app name for app inter connection.
   * </pre>
   *
   * <code>optional string app_name = 16;</code>
   * @return Whether the appName field is set.
   */
  boolean hasAppName();
  /**
   * <pre>
   * app name for app inter connection.
   * </pre>
   *
   * <code>optional string app_name = 16;</code>
   * @return The appName.
   */
  java.lang.String getAppName();
  /**
   * <pre>
   * app name for app inter connection.
   * </pre>
   *
   * <code>optional string app_name = 16;</code>
   * @return The bytes for appName.
   */
  com.google.protobuf.ByteString
      getAppNameBytes();

  /**
   * <pre>
   * app version code
   * </pre>
   *
   * <code>optional int32 app_version_code = 17;</code>
   * @return Whether the appVersionCode field is set.
   */
  boolean hasAppVersionCode();
  /**
   * <pre>
   * app version code
   * </pre>
   *
   * <code>optional int32 app_version_code = 17;</code>
   * @return The appVersionCode.
   */
  int getAppVersionCode();

  /**
   * <pre>
   * app version name
   * </pre>
   *
   * <code>optional string app_version_name = 18;</code>
   * @return Whether the appVersionName field is set.
   */
  boolean hasAppVersionName();
  /**
   * <pre>
   * app version name
   * </pre>
   *
   * <code>optional string app_version_name = 18;</code>
   * @return The appVersionName.
   */
  java.lang.String getAppVersionName();
  /**
   * <pre>
   * app version name
   * </pre>
   *
   * <code>optional string app_version_name = 18;</code>
   * @return The bytes for appVersionName.
   */
  com.google.protobuf.ByteString
      getAppVersionNameBytes();
}
