// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocalNetDevice.proto

package com.nesp.sdk.kotlin.localnet.device.protocol;

/**
 * Protobuf type {@code com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice}
 */
public final class LocalNetDevice extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice)
    LocalNetDeviceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocalNetDevice.newBuilder() to construct.
  private LocalNetDevice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocalNetDevice() {
    did_ = "";
    uid_ = "";
    ip_ = "";
    name_ = "";
    model_ = "";
    brand_ = "";
    board_ = "";
    systemName_ = "";
    systemVersionName_ = "";
    systemArch_ = "";
    appName_ = "";
    appVersionName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LocalNetDevice();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LocalNetDevice(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            did_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            uid_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            ip_ = s;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            udpPort_ = input.readInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            flag_ = input.readInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            linkedCount_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000040;
            name_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000080;
            model_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000100;
            brand_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000200;
            board_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000400;
            systemName_ = s;
            break;
          }
          case 96: {
            bitField0_ |= 0x00000800;
            systemVersionCode_ = input.readInt32();
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00001000;
            systemVersionName_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00002000;
            systemArch_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00004000;
            appName_ = s;
            break;
          }
          case 128: {
            bitField0_ |= 0x00008000;
            appVersionCode_ = input.readInt32();
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00010000;
            appVersionName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDeviceOuterClass.internal_static_com_nesp_sdk_kotlin_localnet_device_protocol_LocalNetDevice_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDeviceOuterClass.internal_static_com_nesp_sdk_kotlin_localnet_device_protocol_LocalNetDevice_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice.class, com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice.Builder.class);
  }

  private int bitField0_;
  public static final int DID_FIELD_NUMBER = 1;
  private volatile java.lang.Object did_;
  /**
   * <pre>
   * device identifier.
   * </pre>
   *
   * <code>optional string did = 1;</code>
   * @return Whether the did field is set.
   */
  @java.lang.Override
  public boolean hasDid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * device identifier.
   * </pre>
   *
   * <code>optional string did = 1;</code>
   * @return The did.
   */
  @java.lang.Override
  public java.lang.String getDid() {
    java.lang.Object ref = did_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      did_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * device identifier.
   * </pre>
   *
   * <code>optional string did = 1;</code>
   * @return The bytes for did.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDidBytes() {
    java.lang.Object ref = did_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      did_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UID_FIELD_NUMBER = 2;
  private volatile java.lang.Object uid_;
  /**
   * <pre>
   * user id, empty if user is not login.
   * </pre>
   *
   * <code>optional string uid = 2;</code>
   * @return Whether the uid field is set.
   */
  @java.lang.Override
  public boolean hasUid() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * user id, empty if user is not login.
   * </pre>
   *
   * <code>optional string uid = 2;</code>
   * @return The uid.
   */
  @java.lang.Override
  public java.lang.String getUid() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * user id, empty if user is not login.
   * </pre>
   *
   * <code>optional string uid = 2;</code>
   * @return The bytes for uid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUidBytes() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IP_FIELD_NUMBER = 3;
  private volatile java.lang.Object ip_;
  /**
   * <pre>
   * device ip address.
   * </pre>
   *
   * <code>optional string ip = 3;</code>
   * @return Whether the ip field is set.
   */
  @java.lang.Override
  public boolean hasIp() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * device ip address.
   * </pre>
   *
   * <code>optional string ip = 3;</code>
   * @return The ip.
   */
  @java.lang.Override
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * device ip address.
   * </pre>
   *
   * <code>optional string ip = 3;</code>
   * @return The bytes for ip.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UDP_PORT_FIELD_NUMBER = 4;
  private int udpPort_;
  /**
   * <pre>
   * port for udp
   * </pre>
   *
   * <code>optional int32 udp_port = 4;</code>
   * @return Whether the udpPort field is set.
   */
  @java.lang.Override
  public boolean hasUdpPort() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * port for udp
   * </pre>
   *
   * <code>optional int32 udp_port = 4;</code>
   * @return The udpPort.
   */
  @java.lang.Override
  public int getUdpPort() {
    return udpPort_;
  }

  public static final int FLAG_FIELD_NUMBER = 5;
  private int flag_;
  /**
   * <pre>
   * flag for addition information
   * </pre>
   *
   * <code>optional int32 flag = 5;</code>
   * @return Whether the flag field is set.
   */
  @java.lang.Override
  public boolean hasFlag() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * flag for addition information
   * </pre>
   *
   * <code>optional int32 flag = 5;</code>
   * @return The flag.
   */
  @java.lang.Override
  public int getFlag() {
    return flag_;
  }

  public static final int LINKED_COUNT_FIELD_NUMBER = 6;
  private int linkedCount_;
  /**
   * <pre>
   * device linked count, -1 is not enabled.
   * </pre>
   *
   * <code>optional int32 linked_count = 6;</code>
   * @return Whether the linkedCount field is set.
   */
  @java.lang.Override
  public boolean hasLinkedCount() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * device linked count, -1 is not enabled.
   * </pre>
   *
   * <code>optional int32 linked_count = 6;</code>
   * @return The linkedCount.
   */
  @java.lang.Override
  public int getLinkedCount() {
    return linkedCount_;
  }

  public static final int NAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * device name.
   * </pre>
   *
   * <code>optional string name = 7;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * device name.
   * </pre>
   *
   * <code>optional string name = 7;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * device name.
   * </pre>
   *
   * <code>optional string name = 7;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_FIELD_NUMBER = 8;
  private volatile java.lang.Object model_;
  /**
   * <pre>
   * device model.
   * </pre>
   *
   * <code>optional string model = 8;</code>
   * @return Whether the model field is set.
   */
  @java.lang.Override
  public boolean hasModel() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <pre>
   * device model.
   * </pre>
   *
   * <code>optional string model = 8;</code>
   * @return The model.
   */
  @java.lang.Override
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * device model.
   * </pre>
   *
   * <code>optional string model = 8;</code>
   * @return The bytes for model.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BRAND_FIELD_NUMBER = 9;
  private volatile java.lang.Object brand_;
  /**
   * <pre>
   * device machine brand
   * </pre>
   *
   * <code>optional string brand = 9;</code>
   * @return Whether the brand field is set.
   */
  @java.lang.Override
  public boolean hasBrand() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <pre>
   * device machine brand
   * </pre>
   *
   * <code>optional string brand = 9;</code>
   * @return The brand.
   */
  @java.lang.Override
  public java.lang.String getBrand() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      brand_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * device machine brand
   * </pre>
   *
   * <code>optional string brand = 9;</code>
   * @return The bytes for brand.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBrandBytes() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      brand_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOARD_FIELD_NUMBER = 10;
  private volatile java.lang.Object board_;
  /**
   * <pre>
   * device board
   * </pre>
   *
   * <code>optional string board = 10;</code>
   * @return Whether the board field is set.
   */
  @java.lang.Override
  public boolean hasBoard() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <pre>
   * device board
   * </pre>
   *
   * <code>optional string board = 10;</code>
   * @return The board.
   */
  @java.lang.Override
  public java.lang.String getBoard() {
    java.lang.Object ref = board_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      board_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * device board
   * </pre>
   *
   * <code>optional string board = 10;</code>
   * @return The bytes for board.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBoardBytes() {
    java.lang.Object ref = board_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      board_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYSTEM_NAME_FIELD_NUMBER = 11;
  private volatile java.lang.Object systemName_;
  /**
   * <pre>
   * system name.
   * </pre>
   *
   * <code>optional string system_name = 11;</code>
   * @return Whether the systemName field is set.
   */
  @java.lang.Override
  public boolean hasSystemName() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <pre>
   * system name.
   * </pre>
   *
   * <code>optional string system_name = 11;</code>
   * @return The systemName.
   */
  @java.lang.Override
  public java.lang.String getSystemName() {
    java.lang.Object ref = systemName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      systemName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * system name.
   * </pre>
   *
   * <code>optional string system_name = 11;</code>
   * @return The bytes for systemName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSystemNameBytes() {
    java.lang.Object ref = systemName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      systemName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYSTEM_VERSION_CODE_FIELD_NUMBER = 12;
  private int systemVersionCode_;
  /**
   * <pre>
   * system version code
   * </pre>
   *
   * <code>optional int32 system_version_code = 12;</code>
   * @return Whether the systemVersionCode field is set.
   */
  @java.lang.Override
  public boolean hasSystemVersionCode() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <pre>
   * system version code
   * </pre>
   *
   * <code>optional int32 system_version_code = 12;</code>
   * @return The systemVersionCode.
   */
  @java.lang.Override
  public int getSystemVersionCode() {
    return systemVersionCode_;
  }

  public static final int SYSTEM_VERSION_NAME_FIELD_NUMBER = 13;
  private volatile java.lang.Object systemVersionName_;
  /**
   * <pre>
   * system version name
   * </pre>
   *
   * <code>optional string system_version_name = 13;</code>
   * @return Whether the systemVersionName field is set.
   */
  @java.lang.Override
  public boolean hasSystemVersionName() {
    return ((bitField0_ & 0x00001000) != 0);
  }
  /**
   * <pre>
   * system version name
   * </pre>
   *
   * <code>optional string system_version_name = 13;</code>
   * @return The systemVersionName.
   */
  @java.lang.Override
  public java.lang.String getSystemVersionName() {
    java.lang.Object ref = systemVersionName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      systemVersionName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * system version name
   * </pre>
   *
   * <code>optional string system_version_name = 13;</code>
   * @return The bytes for systemVersionName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSystemVersionNameBytes() {
    java.lang.Object ref = systemVersionName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      systemVersionName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYSTEM_ARCH_FIELD_NUMBER = 14;
  private volatile java.lang.Object systemArch_;
  /**
   * <pre>
   * system arch
   * </pre>
   *
   * <code>optional string system_arch = 14;</code>
   * @return Whether the systemArch field is set.
   */
  @java.lang.Override
  public boolean hasSystemArch() {
    return ((bitField0_ & 0x00002000) != 0);
  }
  /**
   * <pre>
   * system arch
   * </pre>
   *
   * <code>optional string system_arch = 14;</code>
   * @return The systemArch.
   */
  @java.lang.Override
  public java.lang.String getSystemArch() {
    java.lang.Object ref = systemArch_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      systemArch_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * system arch
   * </pre>
   *
   * <code>optional string system_arch = 14;</code>
   * @return The bytes for systemArch.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSystemArchBytes() {
    java.lang.Object ref = systemArch_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      systemArch_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APP_NAME_FIELD_NUMBER = 15;
  private volatile java.lang.Object appName_;
  /**
   * <pre>
   * app name for app inter connection.
   * </pre>
   *
   * <code>optional string app_name = 15;</code>
   * @return Whether the appName field is set.
   */
  @java.lang.Override
  public boolean hasAppName() {
    return ((bitField0_ & 0x00004000) != 0);
  }
  /**
   * <pre>
   * app name for app inter connection.
   * </pre>
   *
   * <code>optional string app_name = 15;</code>
   * @return The appName.
   */
  @java.lang.Override
  public java.lang.String getAppName() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * app name for app inter connection.
   * </pre>
   *
   * <code>optional string app_name = 15;</code>
   * @return The bytes for appName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppNameBytes() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APP_VERSION_CODE_FIELD_NUMBER = 16;
  private int appVersionCode_;
  /**
   * <pre>
   * app version code
   * </pre>
   *
   * <code>optional int32 app_version_code = 16;</code>
   * @return Whether the appVersionCode field is set.
   */
  @java.lang.Override
  public boolean hasAppVersionCode() {
    return ((bitField0_ & 0x00008000) != 0);
  }
  /**
   * <pre>
   * app version code
   * </pre>
   *
   * <code>optional int32 app_version_code = 16;</code>
   * @return The appVersionCode.
   */
  @java.lang.Override
  public int getAppVersionCode() {
    return appVersionCode_;
  }

  public static final int APP_VERSION_NAME_FIELD_NUMBER = 17;
  private volatile java.lang.Object appVersionName_;
  /**
   * <pre>
   * app version name
   * </pre>
   *
   * <code>optional string app_version_name = 17;</code>
   * @return Whether the appVersionName field is set.
   */
  @java.lang.Override
  public boolean hasAppVersionName() {
    return ((bitField0_ & 0x00010000) != 0);
  }
  /**
   * <pre>
   * app version name
   * </pre>
   *
   * <code>optional string app_version_name = 17;</code>
   * @return The appVersionName.
   */
  @java.lang.Override
  public java.lang.String getAppVersionName() {
    java.lang.Object ref = appVersionName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appVersionName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * app version name
   * </pre>
   *
   * <code>optional string app_version_name = 17;</code>
   * @return The bytes for appVersionName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppVersionNameBytes() {
    java.lang.Object ref = appVersionName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appVersionName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, did_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uid_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, udpPort_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, flag_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt32(6, linkedCount_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, name_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, model_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, brand_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, board_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, systemName_);
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      output.writeInt32(12, systemVersionCode_);
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, systemVersionName_);
    }
    if (((bitField0_ & 0x00002000) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, systemArch_);
    }
    if (((bitField0_ & 0x00004000) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, appName_);
    }
    if (((bitField0_ & 0x00008000) != 0)) {
      output.writeInt32(16, appVersionCode_);
    }
    if (((bitField0_ & 0x00010000) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, appVersionName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, did_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uid_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, udpPort_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, flag_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, linkedCount_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, name_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, model_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, brand_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, board_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, systemName_);
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, systemVersionCode_);
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, systemVersionName_);
    }
    if (((bitField0_ & 0x00002000) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, systemArch_);
    }
    if (((bitField0_ & 0x00004000) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, appName_);
    }
    if (((bitField0_ & 0x00008000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, appVersionCode_);
    }
    if (((bitField0_ & 0x00010000) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, appVersionName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice)) {
      return super.equals(obj);
    }
    com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice other = (com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice) obj;

    if (hasDid() != other.hasDid()) return false;
    if (hasDid()) {
      if (!getDid()
          .equals(other.getDid())) return false;
    }
    if (hasUid() != other.hasUid()) return false;
    if (hasUid()) {
      if (!getUid()
          .equals(other.getUid())) return false;
    }
    if (hasIp() != other.hasIp()) return false;
    if (hasIp()) {
      if (!getIp()
          .equals(other.getIp())) return false;
    }
    if (hasUdpPort() != other.hasUdpPort()) return false;
    if (hasUdpPort()) {
      if (getUdpPort()
          != other.getUdpPort()) return false;
    }
    if (hasFlag() != other.hasFlag()) return false;
    if (hasFlag()) {
      if (getFlag()
          != other.getFlag()) return false;
    }
    if (hasLinkedCount() != other.hasLinkedCount()) return false;
    if (hasLinkedCount()) {
      if (getLinkedCount()
          != other.getLinkedCount()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasModel() != other.hasModel()) return false;
    if (hasModel()) {
      if (!getModel()
          .equals(other.getModel())) return false;
    }
    if (hasBrand() != other.hasBrand()) return false;
    if (hasBrand()) {
      if (!getBrand()
          .equals(other.getBrand())) return false;
    }
    if (hasBoard() != other.hasBoard()) return false;
    if (hasBoard()) {
      if (!getBoard()
          .equals(other.getBoard())) return false;
    }
    if (hasSystemName() != other.hasSystemName()) return false;
    if (hasSystemName()) {
      if (!getSystemName()
          .equals(other.getSystemName())) return false;
    }
    if (hasSystemVersionCode() != other.hasSystemVersionCode()) return false;
    if (hasSystemVersionCode()) {
      if (getSystemVersionCode()
          != other.getSystemVersionCode()) return false;
    }
    if (hasSystemVersionName() != other.hasSystemVersionName()) return false;
    if (hasSystemVersionName()) {
      if (!getSystemVersionName()
          .equals(other.getSystemVersionName())) return false;
    }
    if (hasSystemArch() != other.hasSystemArch()) return false;
    if (hasSystemArch()) {
      if (!getSystemArch()
          .equals(other.getSystemArch())) return false;
    }
    if (hasAppName() != other.hasAppName()) return false;
    if (hasAppName()) {
      if (!getAppName()
          .equals(other.getAppName())) return false;
    }
    if (hasAppVersionCode() != other.hasAppVersionCode()) return false;
    if (hasAppVersionCode()) {
      if (getAppVersionCode()
          != other.getAppVersionCode()) return false;
    }
    if (hasAppVersionName() != other.hasAppVersionName()) return false;
    if (hasAppVersionName()) {
      if (!getAppVersionName()
          .equals(other.getAppVersionName())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDid()) {
      hash = (37 * hash) + DID_FIELD_NUMBER;
      hash = (53 * hash) + getDid().hashCode();
    }
    if (hasUid()) {
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
    }
    if (hasIp()) {
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
    }
    if (hasUdpPort()) {
      hash = (37 * hash) + UDP_PORT_FIELD_NUMBER;
      hash = (53 * hash) + getUdpPort();
    }
    if (hasFlag()) {
      hash = (37 * hash) + FLAG_FIELD_NUMBER;
      hash = (53 * hash) + getFlag();
    }
    if (hasLinkedCount()) {
      hash = (37 * hash) + LINKED_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getLinkedCount();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasModel()) {
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
    }
    if (hasBrand()) {
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
    }
    if (hasBoard()) {
      hash = (37 * hash) + BOARD_FIELD_NUMBER;
      hash = (53 * hash) + getBoard().hashCode();
    }
    if (hasSystemName()) {
      hash = (37 * hash) + SYSTEM_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSystemName().hashCode();
    }
    if (hasSystemVersionCode()) {
      hash = (37 * hash) + SYSTEM_VERSION_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getSystemVersionCode();
    }
    if (hasSystemVersionName()) {
      hash = (37 * hash) + SYSTEM_VERSION_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSystemVersionName().hashCode();
    }
    if (hasSystemArch()) {
      hash = (37 * hash) + SYSTEM_ARCH_FIELD_NUMBER;
      hash = (53 * hash) + getSystemArch().hashCode();
    }
    if (hasAppName()) {
      hash = (37 * hash) + APP_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getAppName().hashCode();
    }
    if (hasAppVersionCode()) {
      hash = (37 * hash) + APP_VERSION_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getAppVersionCode();
    }
    if (hasAppVersionName()) {
      hash = (37 * hash) + APP_VERSION_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getAppVersionName().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice)
      com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDeviceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDeviceOuterClass.internal_static_com_nesp_sdk_kotlin_localnet_device_protocol_LocalNetDevice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDeviceOuterClass.internal_static_com_nesp_sdk_kotlin_localnet_device_protocol_LocalNetDevice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice.class, com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice.Builder.class);
    }

    // Construct using com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      did_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      uid_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      ip_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      udpPort_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      flag_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      linkedCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      model_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      brand_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      board_ = "";
      bitField0_ = (bitField0_ & ~0x00000200);
      systemName_ = "";
      bitField0_ = (bitField0_ & ~0x00000400);
      systemVersionCode_ = 0;
      bitField0_ = (bitField0_ & ~0x00000800);
      systemVersionName_ = "";
      bitField0_ = (bitField0_ & ~0x00001000);
      systemArch_ = "";
      bitField0_ = (bitField0_ & ~0x00002000);
      appName_ = "";
      bitField0_ = (bitField0_ & ~0x00004000);
      appVersionCode_ = 0;
      bitField0_ = (bitField0_ & ~0x00008000);
      appVersionName_ = "";
      bitField0_ = (bitField0_ & ~0x00010000);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDeviceOuterClass.internal_static_com_nesp_sdk_kotlin_localnet_device_protocol_LocalNetDevice_descriptor;
    }

    @java.lang.Override
    public com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice getDefaultInstanceForType() {
      return com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice.getDefaultInstance();
    }

    @java.lang.Override
    public com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice build() {
      com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice buildPartial() {
      com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice result = new com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.did_ = did_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.uid_ = uid_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.ip_ = ip_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.udpPort_ = udpPort_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.flag_ = flag_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.linkedCount_ = linkedCount_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        to_bitField0_ |= 0x00000040;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        to_bitField0_ |= 0x00000080;
      }
      result.model_ = model_;
      if (((from_bitField0_ & 0x00000100) != 0)) {
        to_bitField0_ |= 0x00000100;
      }
      result.brand_ = brand_;
      if (((from_bitField0_ & 0x00000200) != 0)) {
        to_bitField0_ |= 0x00000200;
      }
      result.board_ = board_;
      if (((from_bitField0_ & 0x00000400) != 0)) {
        to_bitField0_ |= 0x00000400;
      }
      result.systemName_ = systemName_;
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.systemVersionCode_ = systemVersionCode_;
        to_bitField0_ |= 0x00000800;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        to_bitField0_ |= 0x00001000;
      }
      result.systemVersionName_ = systemVersionName_;
      if (((from_bitField0_ & 0x00002000) != 0)) {
        to_bitField0_ |= 0x00002000;
      }
      result.systemArch_ = systemArch_;
      if (((from_bitField0_ & 0x00004000) != 0)) {
        to_bitField0_ |= 0x00004000;
      }
      result.appName_ = appName_;
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.appVersionCode_ = appVersionCode_;
        to_bitField0_ |= 0x00008000;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        to_bitField0_ |= 0x00010000;
      }
      result.appVersionName_ = appVersionName_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice) {
        return mergeFrom((com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice other) {
      if (other == com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice.getDefaultInstance()) return this;
      if (other.hasDid()) {
        bitField0_ |= 0x00000001;
        did_ = other.did_;
        onChanged();
      }
      if (other.hasUid()) {
        bitField0_ |= 0x00000002;
        uid_ = other.uid_;
        onChanged();
      }
      if (other.hasIp()) {
        bitField0_ |= 0x00000004;
        ip_ = other.ip_;
        onChanged();
      }
      if (other.hasUdpPort()) {
        setUdpPort(other.getUdpPort());
      }
      if (other.hasFlag()) {
        setFlag(other.getFlag());
      }
      if (other.hasLinkedCount()) {
        setLinkedCount(other.getLinkedCount());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000040;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasModel()) {
        bitField0_ |= 0x00000080;
        model_ = other.model_;
        onChanged();
      }
      if (other.hasBrand()) {
        bitField0_ |= 0x00000100;
        brand_ = other.brand_;
        onChanged();
      }
      if (other.hasBoard()) {
        bitField0_ |= 0x00000200;
        board_ = other.board_;
        onChanged();
      }
      if (other.hasSystemName()) {
        bitField0_ |= 0x00000400;
        systemName_ = other.systemName_;
        onChanged();
      }
      if (other.hasSystemVersionCode()) {
        setSystemVersionCode(other.getSystemVersionCode());
      }
      if (other.hasSystemVersionName()) {
        bitField0_ |= 0x00001000;
        systemVersionName_ = other.systemVersionName_;
        onChanged();
      }
      if (other.hasSystemArch()) {
        bitField0_ |= 0x00002000;
        systemArch_ = other.systemArch_;
        onChanged();
      }
      if (other.hasAppName()) {
        bitField0_ |= 0x00004000;
        appName_ = other.appName_;
        onChanged();
      }
      if (other.hasAppVersionCode()) {
        setAppVersionCode(other.getAppVersionCode());
      }
      if (other.hasAppVersionName()) {
        bitField0_ |= 0x00010000;
        appVersionName_ = other.appVersionName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object did_ = "";
    /**
     * <pre>
     * device identifier.
     * </pre>
     *
     * <code>optional string did = 1;</code>
     * @return Whether the did field is set.
     */
    public boolean hasDid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * device identifier.
     * </pre>
     *
     * <code>optional string did = 1;</code>
     * @return The did.
     */
    public java.lang.String getDid() {
      java.lang.Object ref = did_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        did_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * device identifier.
     * </pre>
     *
     * <code>optional string did = 1;</code>
     * @return The bytes for did.
     */
    public com.google.protobuf.ByteString
        getDidBytes() {
      java.lang.Object ref = did_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        did_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * device identifier.
     * </pre>
     *
     * <code>optional string did = 1;</code>
     * @param value The did to set.
     * @return This builder for chaining.
     */
    public Builder setDid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      did_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device identifier.
     * </pre>
     *
     * <code>optional string did = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      did_ = getDefaultInstance().getDid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device identifier.
     * </pre>
     *
     * <code>optional string did = 1;</code>
     * @param value The bytes for did to set.
     * @return This builder for chaining.
     */
    public Builder setDidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      did_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object uid_ = "";
    /**
     * <pre>
     * user id, empty if user is not login.
     * </pre>
     *
     * <code>optional string uid = 2;</code>
     * @return Whether the uid field is set.
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * user id, empty if user is not login.
     * </pre>
     *
     * <code>optional string uid = 2;</code>
     * @return The uid.
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * user id, empty if user is not login.
     * </pre>
     *
     * <code>optional string uid = 2;</code>
     * @return The bytes for uid.
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * user id, empty if user is not login.
     * </pre>
     *
     * <code>optional string uid = 2;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * user id, empty if user is not login.
     * </pre>
     *
     * <code>optional string uid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      uid_ = getDefaultInstance().getUid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * user id, empty if user is not login.
     * </pre>
     *
     * <code>optional string uid = 2;</code>
     * @param value The bytes for uid to set.
     * @return This builder for chaining.
     */
    public Builder setUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      uid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ip_ = "";
    /**
     * <pre>
     * device ip address.
     * </pre>
     *
     * <code>optional string ip = 3;</code>
     * @return Whether the ip field is set.
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * device ip address.
     * </pre>
     *
     * <code>optional string ip = 3;</code>
     * @return The ip.
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * device ip address.
     * </pre>
     *
     * <code>optional string ip = 3;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * device ip address.
     * </pre>
     *
     * <code>optional string ip = 3;</code>
     * @param value The ip to set.
     * @return This builder for chaining.
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device ip address.
     * </pre>
     *
     * <code>optional string ip = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device ip address.
     * </pre>
     *
     * <code>optional string ip = 3;</code>
     * @param value The bytes for ip to set.
     * @return This builder for chaining.
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      ip_ = value;
      onChanged();
      return this;
    }

    private int udpPort_ ;
    /**
     * <pre>
     * port for udp
     * </pre>
     *
     * <code>optional int32 udp_port = 4;</code>
     * @return Whether the udpPort field is set.
     */
    @java.lang.Override
    public boolean hasUdpPort() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * port for udp
     * </pre>
     *
     * <code>optional int32 udp_port = 4;</code>
     * @return The udpPort.
     */
    @java.lang.Override
    public int getUdpPort() {
      return udpPort_;
    }
    /**
     * <pre>
     * port for udp
     * </pre>
     *
     * <code>optional int32 udp_port = 4;</code>
     * @param value The udpPort to set.
     * @return This builder for chaining.
     */
    public Builder setUdpPort(int value) {
      bitField0_ |= 0x00000008;
      udpPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * port for udp
     * </pre>
     *
     * <code>optional int32 udp_port = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUdpPort() {
      bitField0_ = (bitField0_ & ~0x00000008);
      udpPort_ = 0;
      onChanged();
      return this;
    }

    private int flag_ ;
    /**
     * <pre>
     * flag for addition information
     * </pre>
     *
     * <code>optional int32 flag = 5;</code>
     * @return Whether the flag field is set.
     */
    @java.lang.Override
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * flag for addition information
     * </pre>
     *
     * <code>optional int32 flag = 5;</code>
     * @return The flag.
     */
    @java.lang.Override
    public int getFlag() {
      return flag_;
    }
    /**
     * <pre>
     * flag for addition information
     * </pre>
     *
     * <code>optional int32 flag = 5;</code>
     * @param value The flag to set.
     * @return This builder for chaining.
     */
    public Builder setFlag(int value) {
      bitField0_ |= 0x00000010;
      flag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * flag for addition information
     * </pre>
     *
     * <code>optional int32 flag = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlag() {
      bitField0_ = (bitField0_ & ~0x00000010);
      flag_ = 0;
      onChanged();
      return this;
    }

    private int linkedCount_ ;
    /**
     * <pre>
     * device linked count, -1 is not enabled.
     * </pre>
     *
     * <code>optional int32 linked_count = 6;</code>
     * @return Whether the linkedCount field is set.
     */
    @java.lang.Override
    public boolean hasLinkedCount() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * device linked count, -1 is not enabled.
     * </pre>
     *
     * <code>optional int32 linked_count = 6;</code>
     * @return The linkedCount.
     */
    @java.lang.Override
    public int getLinkedCount() {
      return linkedCount_;
    }
    /**
     * <pre>
     * device linked count, -1 is not enabled.
     * </pre>
     *
     * <code>optional int32 linked_count = 6;</code>
     * @param value The linkedCount to set.
     * @return This builder for chaining.
     */
    public Builder setLinkedCount(int value) {
      bitField0_ |= 0x00000020;
      linkedCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device linked count, -1 is not enabled.
     * </pre>
     *
     * <code>optional int32 linked_count = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLinkedCount() {
      bitField0_ = (bitField0_ & ~0x00000020);
      linkedCount_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * device name.
     * </pre>
     *
     * <code>optional string name = 7;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * device name.
     * </pre>
     *
     * <code>optional string name = 7;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * device name.
     * </pre>
     *
     * <code>optional string name = 7;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * device name.
     * </pre>
     *
     * <code>optional string name = 7;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device name.
     * </pre>
     *
     * <code>optional string name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000040);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device name.
     * </pre>
     *
     * <code>optional string name = 7;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000040;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object model_ = "";
    /**
     * <pre>
     * device model.
     * </pre>
     *
     * <code>optional string model = 8;</code>
     * @return Whether the model field is set.
     */
    public boolean hasModel() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * device model.
     * </pre>
     *
     * <code>optional string model = 8;</code>
     * @return The model.
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * device model.
     * </pre>
     *
     * <code>optional string model = 8;</code>
     * @return The bytes for model.
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * device model.
     * </pre>
     *
     * <code>optional string model = 8;</code>
     * @param value The model to set.
     * @return This builder for chaining.
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      model_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device model.
     * </pre>
     *
     * <code>optional string model = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearModel() {
      bitField0_ = (bitField0_ & ~0x00000080);
      model_ = getDefaultInstance().getModel();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device model.
     * </pre>
     *
     * <code>optional string model = 8;</code>
     * @param value The bytes for model to set.
     * @return This builder for chaining.
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000080;
      model_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object brand_ = "";
    /**
     * <pre>
     * device machine brand
     * </pre>
     *
     * <code>optional string brand = 9;</code>
     * @return Whether the brand field is set.
     */
    public boolean hasBrand() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * device machine brand
     * </pre>
     *
     * <code>optional string brand = 9;</code>
     * @return The brand.
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * device machine brand
     * </pre>
     *
     * <code>optional string brand = 9;</code>
     * @return The bytes for brand.
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * device machine brand
     * </pre>
     *
     * <code>optional string brand = 9;</code>
     * @param value The brand to set.
     * @return This builder for chaining.
     */
    public Builder setBrand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      brand_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device machine brand
     * </pre>
     *
     * <code>optional string brand = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrand() {
      bitField0_ = (bitField0_ & ~0x00000100);
      brand_ = getDefaultInstance().getBrand();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device machine brand
     * </pre>
     *
     * <code>optional string brand = 9;</code>
     * @param value The bytes for brand to set.
     * @return This builder for chaining.
     */
    public Builder setBrandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000100;
      brand_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object board_ = "";
    /**
     * <pre>
     * device board
     * </pre>
     *
     * <code>optional string board = 10;</code>
     * @return Whether the board field is set.
     */
    public boolean hasBoard() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     * device board
     * </pre>
     *
     * <code>optional string board = 10;</code>
     * @return The board.
     */
    public java.lang.String getBoard() {
      java.lang.Object ref = board_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        board_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * device board
     * </pre>
     *
     * <code>optional string board = 10;</code>
     * @return The bytes for board.
     */
    public com.google.protobuf.ByteString
        getBoardBytes() {
      java.lang.Object ref = board_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        board_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * device board
     * </pre>
     *
     * <code>optional string board = 10;</code>
     * @param value The board to set.
     * @return This builder for chaining.
     */
    public Builder setBoard(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      board_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device board
     * </pre>
     *
     * <code>optional string board = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoard() {
      bitField0_ = (bitField0_ & ~0x00000200);
      board_ = getDefaultInstance().getBoard();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * device board
     * </pre>
     *
     * <code>optional string board = 10;</code>
     * @param value The bytes for board to set.
     * @return This builder for chaining.
     */
    public Builder setBoardBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000200;
      board_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object systemName_ = "";
    /**
     * <pre>
     * system name.
     * </pre>
     *
     * <code>optional string system_name = 11;</code>
     * @return Whether the systemName field is set.
     */
    public boolean hasSystemName() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <pre>
     * system name.
     * </pre>
     *
     * <code>optional string system_name = 11;</code>
     * @return The systemName.
     */
    public java.lang.String getSystemName() {
      java.lang.Object ref = systemName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        systemName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * system name.
     * </pre>
     *
     * <code>optional string system_name = 11;</code>
     * @return The bytes for systemName.
     */
    public com.google.protobuf.ByteString
        getSystemNameBytes() {
      java.lang.Object ref = systemName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * system name.
     * </pre>
     *
     * <code>optional string system_name = 11;</code>
     * @param value The systemName to set.
     * @return This builder for chaining.
     */
    public Builder setSystemName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      systemName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * system name.
     * </pre>
     *
     * <code>optional string system_name = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSystemName() {
      bitField0_ = (bitField0_ & ~0x00000400);
      systemName_ = getDefaultInstance().getSystemName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * system name.
     * </pre>
     *
     * <code>optional string system_name = 11;</code>
     * @param value The bytes for systemName to set.
     * @return This builder for chaining.
     */
    public Builder setSystemNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000400;
      systemName_ = value;
      onChanged();
      return this;
    }

    private int systemVersionCode_ ;
    /**
     * <pre>
     * system version code
     * </pre>
     *
     * <code>optional int32 system_version_code = 12;</code>
     * @return Whether the systemVersionCode field is set.
     */
    @java.lang.Override
    public boolean hasSystemVersionCode() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <pre>
     * system version code
     * </pre>
     *
     * <code>optional int32 system_version_code = 12;</code>
     * @return The systemVersionCode.
     */
    @java.lang.Override
    public int getSystemVersionCode() {
      return systemVersionCode_;
    }
    /**
     * <pre>
     * system version code
     * </pre>
     *
     * <code>optional int32 system_version_code = 12;</code>
     * @param value The systemVersionCode to set.
     * @return This builder for chaining.
     */
    public Builder setSystemVersionCode(int value) {
      bitField0_ |= 0x00000800;
      systemVersionCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * system version code
     * </pre>
     *
     * <code>optional int32 system_version_code = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSystemVersionCode() {
      bitField0_ = (bitField0_ & ~0x00000800);
      systemVersionCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object systemVersionName_ = "";
    /**
     * <pre>
     * system version name
     * </pre>
     *
     * <code>optional string system_version_name = 13;</code>
     * @return Whether the systemVersionName field is set.
     */
    public boolean hasSystemVersionName() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <pre>
     * system version name
     * </pre>
     *
     * <code>optional string system_version_name = 13;</code>
     * @return The systemVersionName.
     */
    public java.lang.String getSystemVersionName() {
      java.lang.Object ref = systemVersionName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        systemVersionName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * system version name
     * </pre>
     *
     * <code>optional string system_version_name = 13;</code>
     * @return The bytes for systemVersionName.
     */
    public com.google.protobuf.ByteString
        getSystemVersionNameBytes() {
      java.lang.Object ref = systemVersionName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemVersionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * system version name
     * </pre>
     *
     * <code>optional string system_version_name = 13;</code>
     * @param value The systemVersionName to set.
     * @return This builder for chaining.
     */
    public Builder setSystemVersionName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
      systemVersionName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * system version name
     * </pre>
     *
     * <code>optional string system_version_name = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearSystemVersionName() {
      bitField0_ = (bitField0_ & ~0x00001000);
      systemVersionName_ = getDefaultInstance().getSystemVersionName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * system version name
     * </pre>
     *
     * <code>optional string system_version_name = 13;</code>
     * @param value The bytes for systemVersionName to set.
     * @return This builder for chaining.
     */
    public Builder setSystemVersionNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00001000;
      systemVersionName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object systemArch_ = "";
    /**
     * <pre>
     * system arch
     * </pre>
     *
     * <code>optional string system_arch = 14;</code>
     * @return Whether the systemArch field is set.
     */
    public boolean hasSystemArch() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <pre>
     * system arch
     * </pre>
     *
     * <code>optional string system_arch = 14;</code>
     * @return The systemArch.
     */
    public java.lang.String getSystemArch() {
      java.lang.Object ref = systemArch_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        systemArch_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * system arch
     * </pre>
     *
     * <code>optional string system_arch = 14;</code>
     * @return The bytes for systemArch.
     */
    public com.google.protobuf.ByteString
        getSystemArchBytes() {
      java.lang.Object ref = systemArch_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemArch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * system arch
     * </pre>
     *
     * <code>optional string system_arch = 14;</code>
     * @param value The systemArch to set.
     * @return This builder for chaining.
     */
    public Builder setSystemArch(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
      systemArch_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * system arch
     * </pre>
     *
     * <code>optional string system_arch = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearSystemArch() {
      bitField0_ = (bitField0_ & ~0x00002000);
      systemArch_ = getDefaultInstance().getSystemArch();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * system arch
     * </pre>
     *
     * <code>optional string system_arch = 14;</code>
     * @param value The bytes for systemArch to set.
     * @return This builder for chaining.
     */
    public Builder setSystemArchBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00002000;
      systemArch_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appName_ = "";
    /**
     * <pre>
     * app name for app inter connection.
     * </pre>
     *
     * <code>optional string app_name = 15;</code>
     * @return Whether the appName field is set.
     */
    public boolean hasAppName() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <pre>
     * app name for app inter connection.
     * </pre>
     *
     * <code>optional string app_name = 15;</code>
     * @return The appName.
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * app name for app inter connection.
     * </pre>
     *
     * <code>optional string app_name = 15;</code>
     * @return The bytes for appName.
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * app name for app inter connection.
     * </pre>
     *
     * <code>optional string app_name = 15;</code>
     * @param value The appName to set.
     * @return This builder for chaining.
     */
    public Builder setAppName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
      appName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * app name for app inter connection.
     * </pre>
     *
     * <code>optional string app_name = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppName() {
      bitField0_ = (bitField0_ & ~0x00004000);
      appName_ = getDefaultInstance().getAppName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * app name for app inter connection.
     * </pre>
     *
     * <code>optional string app_name = 15;</code>
     * @param value The bytes for appName to set.
     * @return This builder for chaining.
     */
    public Builder setAppNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00004000;
      appName_ = value;
      onChanged();
      return this;
    }

    private int appVersionCode_ ;
    /**
     * <pre>
     * app version code
     * </pre>
     *
     * <code>optional int32 app_version_code = 16;</code>
     * @return Whether the appVersionCode field is set.
     */
    @java.lang.Override
    public boolean hasAppVersionCode() {
      return ((bitField0_ & 0x00008000) != 0);
    }
    /**
     * <pre>
     * app version code
     * </pre>
     *
     * <code>optional int32 app_version_code = 16;</code>
     * @return The appVersionCode.
     */
    @java.lang.Override
    public int getAppVersionCode() {
      return appVersionCode_;
    }
    /**
     * <pre>
     * app version code
     * </pre>
     *
     * <code>optional int32 app_version_code = 16;</code>
     * @param value The appVersionCode to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersionCode(int value) {
      bitField0_ |= 0x00008000;
      appVersionCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * app version code
     * </pre>
     *
     * <code>optional int32 app_version_code = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppVersionCode() {
      bitField0_ = (bitField0_ & ~0x00008000);
      appVersionCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object appVersionName_ = "";
    /**
     * <pre>
     * app version name
     * </pre>
     *
     * <code>optional string app_version_name = 17;</code>
     * @return Whether the appVersionName field is set.
     */
    public boolean hasAppVersionName() {
      return ((bitField0_ & 0x00010000) != 0);
    }
    /**
     * <pre>
     * app version name
     * </pre>
     *
     * <code>optional string app_version_name = 17;</code>
     * @return The appVersionName.
     */
    public java.lang.String getAppVersionName() {
      java.lang.Object ref = appVersionName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVersionName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * app version name
     * </pre>
     *
     * <code>optional string app_version_name = 17;</code>
     * @return The bytes for appVersionName.
     */
    public com.google.protobuf.ByteString
        getAppVersionNameBytes() {
      java.lang.Object ref = appVersionName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVersionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * app version name
     * </pre>
     *
     * <code>optional string app_version_name = 17;</code>
     * @param value The appVersionName to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersionName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
      appVersionName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * app version name
     * </pre>
     *
     * <code>optional string app_version_name = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppVersionName() {
      bitField0_ = (bitField0_ & ~0x00010000);
      appVersionName_ = getDefaultInstance().getAppVersionName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * app version name
     * </pre>
     *
     * <code>optional string app_version_name = 17;</code>
     * @param value The bytes for appVersionName to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersionNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00010000;
      appVersionName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice)
  }

  // @@protoc_insertion_point(class_scope:com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice)
  private static final com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice();
  }

  public static com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocalNetDevice>
      PARSER = new com.google.protobuf.AbstractParser<LocalNetDevice>() {
    @java.lang.Override
    public LocalNetDevice parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LocalNetDevice(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LocalNetDevice> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocalNetDevice> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nesp.sdk.kotlin.localnet.device.protocol.LocalNetDevice getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

